GRPC_PORT: 50051
REST_PORT: 8081

POSTGRES:
  POSTGRES_USER: root
  POSTGRES_PASSWORD: 1234
  POSTGRES_DB: postgres
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5432

  POSTGRES_MAX_CONN: 10
  POSTGRES_MIN_CONN: 5
